In [1]:
import numpy as np

In [16]:
arr1 = np.arange(0, 5)
arr2 = np.arange(6, 11)

In [17]:
arr1

array([0, 1, 2, 3, 4])

In [18]:
arr2

array([ 6,  7,  8,  9, 10])

In [19]:
# Array addition: arr + arr
arr1 + arr2

array([ 6,  8, 10, 12, 14])

In [20]:
# Array substraction: arr - arr
arr2 - arr1

array([6, 6, 6, 6, 6])

In [21]:
# Array division: arr / arr
arr1 / arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [22]:
# Array square: arr ** 2
arr1 ** 2

array([ 0,  1,  4,  9, 16])

In [23]:
## Operation np.add()
np.add(arr1, arr2)

array([ 6,  8, 10, 12, 14])

In [27]:
## Operation np.substract()
np.subtract(arr1, arr2)

array([-6, -6, -6, -6, -6])

In [28]:
## Operation np.multiply()
np.multiply(arr1, arr2)

array([ 0,  7, 16, 27, 40])

In [29]:
## Operation np.divide()
np.divide(arr1, arr2)

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [30]:
## Operation np.power()
np.power(arr1, arr2)

array([      0,       1,     256,   19683, 1048576])

## Trigonometry functions

In [32]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [33]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [35]:
np.tan(arr1)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [36]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [37]:
np.log(arr1)

C:\Users\naret\AppData\Local\Temp\ipykernel_2008\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

## Comparison - Element wise comparison

In [38]:
np.greater(arr1, arr2)

array([False, False, False, False, False])

In [39]:
np.less(arr1, arr2)

array([ True,  True,  True,  True,  True])