In [ ]:
import numpy as np

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Shape
array_2d.shape

(2, 3)

In [ ]:
# Reshape
array_2d.shape

(2, 3)

In [ ]:
array_1d = np.arange(6)
array_1d

array([0, 1, 2, 3, 4, 5])

In [ ]:
array_reshaped = array_1d.reshape(2, 3)
array_reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Convert back to 1d array - flatten - create a copy
array_reshaped.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Convert back to 1d array - ravel - create a view
array_reshaped.ravel()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Transpose - transpose() 2x3 to 3x2
array_reshaped.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

## Merge multiple arrays

In [ ]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6]])

In [ ]:
array_a

array([[1, 2],
       [3, 4]])

In [ ]:
array_b

array([[5, 6]])

In [ ]:
# Concatenate array_a and array_b
np.concatenate( (array_a, array_b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Vertical stack - vstack()
np.vstack( (array_a, array_b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Horizontal stack - hstack() must have same dimension
array_c = np.array([[7], [8]])
    
np.hstack( (array_a, array_c))

array([[1, 2, 7],
       [3, 4, 8]])

In [ ]:
# 3d stack - dstack() must have same dimension
    
np.dstack( (array_a, array_a))

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

In [ ]:
# stack along new axis -  
np.stack( (array_a, array_a), axis=0)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

## Splitting array into multiple arrays

In [ ]:
# Split array_1d into 3 arrays
np.split(array_1d, 3)

[array([0, 1]), array([2, 3]), array([4, 5])]

In [ ]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Split array horizontally (column) - hsplit()
np.hsplit(array_2d, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [ ]:
# Split array vertically (row) - hsplit()
np.vsplit(array_2d, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [ ]:
#
array_3d = np.stack((array_a, array_a), axis=0)
array_3d.shape

(2, 2, 2)

In [ ]:
array_3d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [ ]:
# Split 3D array - dsplit() along depth axis
np.dsplit(array_3d, 2)

[array([[[1],
         [3]],
 
        [[1],
         [3]]]),
 array([[[2],
         [4]],
 
        [[2],
         [4]]])]

## Insert element into array - delete element from array

In [ ]:
array_1d

array([0, 1, 2, 3, 4, 5])

In [ ]:
# insert 99 at index 2
np.insert(array_1d, 2, 99)

array([ 0,  1, 99,  2,  3,  4,  5])

In [ ]:
# Append 99 at the end of array
np.append(array_1d, 99)

array([ 0,  1,  2,  3,  4,  5, 99])

In [ ]:
# delete an element at index 0
np.delete(array_1d, 0)

array([1, 2, 3, 4, 5])

In [ ]:
# Assign an array to a new variable does not create a copy. Both variables point to the same data
new_array = array_1d
new_array

array([0, 1, 2, 3, 4, 5])

In [ ]:
new_array[0] = 99
new_array

array([99,  1,  2,  3,  4,  5])

In [ ]:
array_1d

array([99,  1,  2,  3,  4,  5])

## A view creates a new array object that looks at the same data as well.

In [ ]:
new_array = array_1d.view()
new_array

array([99,  1,  2,  3,  4,  5])

In [ ]:
new_array[0] = 89
new_array

array([89,  1,  2,  3,  4,  5])

In [ ]:
array_1d

array([89,  1,  2,  3,  4,  5])

## copy() creates a new array and copies the data.

In [ ]:
new_array = array_1d.copy()
new_array

array([89,  1,  2,  3,  4,  5])

In [ ]:
new_array[0] = 29
new_array

array([29,  1,  2,  3,  4,  5])

In [ ]:
array_1d

array([89,  1,  2,  3,  4,  5])

In [ ]:
#
array_i = np.array([1,2,3])
array_j = np.array([[4], [5], [6]])
print('array_i: ')
print(array_i)
print('array_j: ')
print(array_j)

array_i: 
[1 2 3]
array_j: 
[[4]
 [5]
 [6]]


In [ ]:
print(array_i.shape, array_j.shape)

(3,) (3, 1)


In [ ]:
array_i + array_j

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
array_sort = np.array([3, 1, 2])
np.sort(array_sort)

array([1, 2, 3])