In [1]:
import numpy as np

In [2]:
# 1d array
array_1d = np.array([10,20,30,40,50])
array_1d

array([10, 20, 30, 40, 50])

In [ ]:
# element at index 1
array_1d[1]

np.int64(20)

In [4]:
# last element at index -1
array_1d[-1]

np.int64(50)

## Slicing

In [8]:
array_1d

array([10, 20, 30, 40, 50])

In [5]:
# Array from 1 to 3
array_1d[1:3]

array([20, 30])

In [6]:
# Array from beginning to 3
array_1d[:3]

array([10, 20, 30])

In [7]:
# Array from index 2 to the end
array_1d[2:]

array([30, 40, 50])

In [ ]:
# all value [from:to:step]  index step=2 ( get every other value)
array_1d[::2]

array([10, 30, 50])

In [11]:
array_2d = np.array( [
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Access each element using [1][2]
array_2d[1][2]

np.int64(6)

In [15]:
# Access each element using comma sepated index [1,2]
array_2d[1, 2]

np.int64(6)

In [ ]:
# Slicing:  first 2 row (:2), all column (:)
array_2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Slicing:  all row (:), first 2 columns (:2)
array_2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# Slicing:  sub-array : first 2 row (0:2), columns 2 and 3 (1:3)
array_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
array_3d = np.array([
    [ # Depth 0
        [ 1, 2, 3],     # row 0
        [ 4, 5, 6],     # row 1
        
    ],
    [ # Depth 1
        [ 7, 8, 9],     # row 0
        [ 10, 11, 12]   # row 1
    ]
])

In [21]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
array_3d[1][0][2]

np.int64(9)

In [23]:
array_3d[1,0,2]

np.int64(9)

In [26]:
# slicing
array_3d[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# slicing
array_3d[:, 1, :2]

array([[ 4,  5],
       [10, 11]])

## Conditional selection

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6,7, 8,9])

In [29]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# all value less than 5
arr[arr < 5]

array([1, 2, 3, 4])

In [32]:
# all value >= 7
arr[arr >= 7]

array([7, 8, 9])

In [ ]:
# all even values
arr[arr % 2 == 0]

array([2, 4, 6, 8])

In [ ]:
# all odd values 
arr[arr % 2 != 0]

array([1, 3, 5, 7, 9])

In [36]:
# all odd values and > 5
arr[(arr % 2 != 0) & (arr > 5) ]

array([7, 9])

In [39]:
# all values < 3 and > 5
arr[(arr < 3) | (arr > 7) ]

array([1, 2, 8, 9])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6,7, 8,9])
bool_array = arr > 5
arr[bool_array]

array([6, 7, 8, 9])

In [41]:
# get value with index 1, 3, 4
arr = np.array([1, 2, 3, 4, 5, 6,7, 8, 9])
indices = [1, 3, 4]

arr[indices]

array([2, 4, 5])

In [42]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
row_indices = np.array([0, 1, 2]) # list of row 0, 1, 2
col_indices = np.array([0, 1, 2]) # list of col 0, 1, 2
array_2d[row_indices, col_indices] # diagonal value

array([1, 5, 9])