In [1]:
import numpy as np

In [2]:
data = np.array([15, 20, 35, 40, 50, 65, 75, 80, 95])
data

array([15, 20, 35, 40, 50, 65, 75, 80, 95])

In [3]:
# mean()
np.mean(data)

np.float64(52.77777777777778)

In [5]:
# median()
np.median(data)

np.float64(50.0)

In [6]:
# sum()
np.sum(data)

np.int64(475)

In [9]:
# min()
np.min(data)

np.int64(15)

In [11]:
# max()
np.max(data)

np.int64(95)

In [14]:
# std() - standard deviation
np.std(data)

np.float64(26.15244954653293)

In [15]:
# var() - variance
np.var(data)

np.float64(683.9506172839506)

## Anvanced statistics

In [18]:
# percentile() - percentile - 10 percentile
np.percentile(data, 10)

np.float64(19.0)

In [17]:
# percentile() - percentile - 75 percentile
np.percentile(data, 75)

np.float64(75.0)

### correlation coefficient

In [21]:
data_x = np.array([1,2,3,4,5])
data_y = np.array([2,4,6,8,10])

In [23]:
# corrcoef() - correlation coefficient between data_x and data_y
np.corrcoef(data_x, data_y)

array([[1., 1.],
       [1., 1.]])

In [24]:
# cov() - covariance matrix  between data_x and data_y
np.cov(data_x, data_y)

array([[ 2.5,  5. ],
       [ 5. , 10. ]])

### axis=0 - columns, axis=1 - rows

In [25]:
# axis=0 - columns, axis=1 - rows
array_2d = np.array([
    [10, 15, 20],
    [25, 30, 35],    
    [40, 45, 50]
])
array_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [27]:
np.mean(array_2d, axis=0) # along columns

array([25., 30., 35.])

In [28]:
np.mean(array_2d, axis=1) # along rows

array([15., 30., 45.])

In [30]:
# 3D array data
array_3d = np.array([
    [
        [10, 15, 20],
        [25, 30, 35]
    ],
    [
        [40, 45, 50],
        [55, 60, 65]
    ]               
])

In [31]:
np.mean(array_3d, axis=0) # along columns

array([[25., 30., 35.],
       [40., 45., 50.]])

In [32]:
np.mean(array_3d, axis=1) # along rows

array([[17.5, 22.5, 27.5],
       [47.5, 52.5, 57.5]])