In [1]:
import numpy as np

## Array

In [2]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [ ]:
# 2 dimentional arrays or matrices
array_2d = np.array([[1,2,3], [4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Multi dimentional arrays or tensor
array_3d = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
array_3d.ndim

3

In [6]:
array_3d.shape

(2, 2, 2)

In [7]:
array_3d.size

8

In [8]:
array_3d.dtype

dtype('int64')

In [9]:
# 1D Array filled with 0s
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [11]:
# 2D Array filled with 0s
zeros_2d = np.zeros([3, 4])
zeros_2d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# 1D Array filled with 1s
ones_1d = np.ones(5)
ones_1d

array([1., 1., 1., 1., 1.])

In [13]:
# 2D Array filled with 1s
ones_2d = np.ones([3, 4])
ones_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# constant array 3x3 fill with 7
constant_array = np.full((3,3), 7)
constant_array

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(4) * 5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [21]:
# range
range_array = np.arange(10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# range 5 to 55 step 5
range_array = np.arange(5, 55, 5)
range_array

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# .linspace 0..1 
linspace_array = np.linspace(0, 1, 5)
linspace_array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# .linspace 0..100 10 space
# create an array of numbers that are evenly spaced between the set interval
linspace_array = np.linspace(0, 100, 10)
linspace_array

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
# .linspace 0..100 11 space
# create an array of numbers that are evenly spaced between the set interval
linspace_array = np.linspace(0, 100, 11)
linspace_array

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
# 1d array with 5 elements filled with random numbers
np.random.rand(5)

array([0.67123774, 0.13244306, 0.08838593, 0.25044002, 0.55727245])

In [ ]:
# 2d array 3x4 filled with random numbers
np.random.rand(3, 4)

array([[0.06817224, 0.2818756 , 0.86504031, 0.79937446],
       [0.02039631, 0.46569887, 0.80030979, 0.0395825 ],
       [0.94153266, 0.17867698, 0.10515331, 0.89025102]])

In [33]:
# 1d array with 5 elements filled with random numbers between 10 and 50 .randint()
np.random.randint(10, 50, 5)

array([23, 42, 33, 32, 48], dtype=int32)

In [40]:
# 1d array with 5 elements filled with random numbers between 10 and 50 .randint()
# reproducable with seed
np.random.seed(42)
np.random.randint(10, 50, 5)

array([48, 38, 24, 17, 30], dtype=int32)